var model;
var handlers;

$(document).ready(function () {

    function IconAtlasViewModel() {
        var self = this;

        self.strategicIconSource = function (string) { return 'img/strategic_icons/' + 'icon_si_' + string + '.png' }
        self.strategicIcons = ko.observableArray([
            'blip',
            'metal_splat_02',
            'control_point_01',
            'celestial_object',
            'land_barrier',
            'commander',
            'avatar',
            'control_point',
            'metal_spot_preview',
            'anti_nuke_launcher_ammo',
            'nuke_launcher_ammo',
            'SresA1',
            'SrepA1',
            'SrepA3',
            'SrmsA1',
            'SrmpA1',
            'SrmpA3',
            'SradarA1',
            'SradarA2',
            'SradarA3',
            'SoradarA1',
            'SoradarA3',
            'Sdal11',
            'Sdal12',
            'Sdal13',
            'Sdal21',
            'Sdal22',
            'Sdal23',
            'Sdart11',
            'Sdart12',
            'Sdart13',
            'Sdart21',
            'Sdtml22',
            'Sdart23',
            'SdaaA1',
            'SdaaA2',
            'SdaoA1',
            'SdaoA3',
            'SsnlA0',
            'SsndA0',
            'SspeA0',
            'SscmA0',
            'SfucA0',
            'SstpA0',
            'AtransportA2',
            'Afac11',
            'Afac12',
            'Afac13',
            'Afab11',
            'Afab12',
            'Afab13',
            'Afighter11',
            'Afighter12',
            'Agunship11',
            'Abomber13',
            'Ascout12',
            'Afac21',
            'Afac22',
            'Afac23',
            'Afab21',
            'Afab22',
            'Afab23',
            'Afighter21',
            'Afighter22',
            'Afighter23',
            'Abomber21',
            'Abomber22',
            'Abomber23',
            'Ascout21',
            'Xmb3',
            'Bfac11',
            'Bfac12',
            'Bfac13',
            'Bfab11',
            'Bfab12',
            'Bfab13',
            'Bassault11',
            'Bassault12',
            'Bassault13',
            'Bbomb31',
            'Btactical13',
            'Baa31',
            'Baa32',
            'Bscout31',
            'Bao32',
            'Bfac21',
            'Bfac22',
            'Bfac23',
            'Bfab21',
            'Bfab22',
            'Bfab23',
            'Bassault21',
            'Bassault22',
            'Bassault23',
            'Bflame21',
            'Bmortar21',
            'Bsniper23',
            'Bsupport22',
            'Baa21',
            'Baa23',
            'Bscout33',
            'Vfac11',
            'Vfac12',
            'Vfac13',
            'Vfab11',
            'Vfab12',
            'Vfab13',
            'Vassault11',
            'Vassault12',
            'Vassault13',
            'Vsupport11',
            'Vmortar12',
            'Vartillery13',
            'Vaa11',
            'Vaa13',
            'Vscout11',
            'Vao13',
            'Vfac21',
            'Vfac22',
            'Vfac23',
            'Vfab21',
            'Vfab22',
            'Vfab23',
            'Vassault21',
            'Vassault22',
            'Vsupport21',
            'Vsupport22',
            'Vartillery23',
            'Vaa21',
            'Vaa22',
            'Vradar21',
            'Vpd22',
            'Vscout23',
            'Xmb1',
            'Xmb2',
            'Xmb4b',
            'Naa11',
            'Naa13',
            'Nassault11',
            'Nassault12',
            'Nassault13',
            'NdanA1',
            'NdanA2',
            'Nfab11',
            'Nfab12',
            'Nfab13',
            'Nfac11',
            'Nfac12',
            'Nfac13',
            'Nscout11',
            'NsonarA1',
            'Ntactical13',
            'Ntorpedo11',
            'Ntorpedo12',
            'OfaclA0',
            'OfacA0',
            'OfabA0',
            'OtranspA0',
            'OartyA0',
            'ObombA0',
            'ObuzzerA0',
            'OdefsatA0',
            'OdestrA0',
            'OfighterA0',
            'OlaserA0',
            'OradarA1',
            'OradarA2',
            'OrepA0',
            'OrmpA0',
            'SfucB1',
            'SfucB2',
            'SfucV1',
            'SfucV2',
            'Sfamph11',
            'Sfcmb11',
            'Sfnano11',
            'Sfnano21',
            'Bnano31',
            'Vnano11',
            'Bfab1X',
            'Vfab2X'
        ]);

        self.sendIconList = function () {
            var list = model.strategicIcons();
            engine.call('handle_icon_list', list, 52);
        }
    }
    model = new IconAtlasViewModel();
    handlers = {};

    // inject per scene mods
    if (scene_mod_list['icon_atlas'])
        loadMods(scene_mod_list['icon_atlas']);

    // setup send/recv messages and signals
    app.registerWithCoherent(model, handlers);

    // Activates knockout.js
    ko.applyBindings(model);

    model.sendIconList();

});
