
function BuildHotkeyModel() {
    var self = this;

    var FAC=0;
    var UTIL=FAC+6;
    var COMB=UTIL+6;
    var AMMO=COMB+9;
    var SUPER=AMMO+1;
    var VEH=SUPER+2;
    var BOT=VEH+7;
    var AIR=BOT+6;
    var SEA=AIR+7;
    var ORB=SEA+6;
    self.SpecIdToGridMap = ko.observable(
        {
            "/pa/units/land/bot_factory_adv/bot_factory_adv.json": ["factory", 0, FAC+0, 2],
            "/pa/units/land/bot_factory/bot_factory.json": ["factory", 1, FAC+0, 1],
            "/pa/units/land/bot_factory_basic/bot_factory_basic.json": ["factory", 2, FAC+0, 0],
            "/pa/units/land/vehicle_factory_adv/vehicle_factory_adv.json": ["factory", 3, FAC+1, 2],
            "/pa/units/land/vehicle_factory/vehicle_factory.json": ["factory", 4, FAC+1, 1],
            "/pa/units/land/vehicle_factory_basic/vehicle_factory_basic.json": ["factory", 5, FAC+1, 0],
            "/pa/units/air/air_factory_adv/air_factory_adv.json": ["factory", 6, FAC+2, 2],
            "/pa/units/air/air_factory/air_factory.json": ["factory", 7, FAC+2, 1],
            "/pa/units/air/air_factory_basic/air_factory_basic.json": ["factory", 8, FAC+2, 0],
            "/pa/units/sea/naval_factory_adv/naval_factory_adv.json": ["factory", 9, FAC+3, 2],
            "/pa/units/sea/naval_factory/naval_factory.json": ["factory", 11, FAC+3, 1],
            "/pa/units/sea/naval_factory_basic/naval_factory_basic.json": ["factory", 10, FAC+3, 0],
            "/pa/units/land/combat_factory_adv/combat_factory_adv.json": ["factory", 12, FAC+4, 2],
            "/pa/units/land/combat_factory/combat_factory.json": ["factory", 13, FAC+4, 1],
            "/pa/units/land/combat_factory_basic/combat_factory_basic.json": ["factory", 14, FAC+4, 0],
            "/pa/units/land/unit_cannon/unit_cannon.json": ["factory", 15, FAC+5, 2],
            "/pa/units/orbital/orbital_launcher/orbital_launcher.json": ["factory", 16, FAC+5, 0],

            "/pa/units/land/control_module/control_module.json": ["utility", 0, UTIL+0, 2],
            "/pa/units/orbital/delta_v_engine/delta_v_engine.json": ["utility", 1, UTIL+0, 1],
            "/pa/units/land/teleporter/teleporter.json": ["utility", 3, UTIL+0, 0],
            "/pa/units/orbital/deep_space_radar/deep_space_radar.json": ["utility", 4, UTIL+1, 1],
            "/pa/units/orbital/orbital_radar_basic/orbital_radar_basic.json": ["utility", 5, UTIL+1, 0],
            "/pa/units/land/radar_adv/radar_adv.json": ["utility", 6, UTIL+2, 1],
            "/pa/units/land/radar/radar.json": ["utility", 7, UTIL+2, 0],
            "/pa/units/sea/sonar_adv/sonar_adv.json": ["utility", 8, UTIL+3, 1],
            "/pa/units/sea/sonar/sonar.json": ["utility", 9, UTIL+3, 0],
            "/pa/units/land/energy_plant_adv/energy_plant_adv.json": ["utility", 10, UTIL+4, 2],
            "/pa/units/land/energy_plant/energy_plant.json": ["utility", 11, UTIL+4, 1],
            "/pa/units/land/energy_storage/energy_storage.json": ["utility", 12, UTIL+4, 0],
            "/pa/units/land/metal_extractor_adv/metal_extractor_adv.json": ["utility", 13, UTIL+5, 2],
            "/pa/units/land/metal_extractor/metal_extractor.json": ["utility", 14, UTIL+5, 1],
            "/pa/units/land/metal_storage/metal_storage.json": ["utility", 15, UTIL+5, 0],

            "/pa/units/land/land_mine/land_mine.json": ["combat", 15, COMB+0, 1],
            "/pa/units/land/land_barrier/land_barrier.json": ["combat", 16, COMB+0, 0],
            "/pa/units/land/uber_turret/uber_turret.json": ["combat", 0, COMB+1, 2],
            "/pa/units/land/laser_defense_sniper/laser_defense_sniper.json": ["combat", 1, COMB+1, 1],
            "/pa/units/land/laser_defense/laser_defense.json": ["combat", 2, COMB+1, 0],
            "/pa/units/land/laser_defense_adv/laser_defense_adv.json": ["combat", 3, COMB+2, 2],
            "/pa/units/land/mortar_turret/mortar_turret.json": ["combat", 4, COMB+2, 1],
            "/pa/units/land/laser_defense_single/laser_defense_single.json": ["combat", 5, COMB+2, 0],
            "/pa/units/land/artillery_long/artillery_long.json": ["combat", 6, COMB+3, 2],
            "/pa/units/land/tactical_missile_launcher/tactical_missile_launcher.json": ["combat", 7, COMB+3, 1],
            "/pa/units/land/artillery_short/artillery_short.json": ["combat", 8, COMB+3, 0],
            "/pa/units/land/plasma_artillery/plasma_artillery.json": ["combat", 9, COMB+4, 2],
            "/pa/units/land/artillery_t1/artillery_t1.json": ["combat", 10, COMB+4, 1],
            "/pa/units/land/air_defense_adv/air_defense_adv.json": ["combat", 11, COMB+5, 1],
            "/pa/units/land/air_defense/air_defense.json": ["combat", 12, COMB+5, 0],
            "/pa/units/sea/torpedo_launcher_adv/torpedo_launcher_adv.json": ["combat", 13, COMB+6, 1],
            "/pa/units/sea/torpedo_launcher/torpedo_launcher.json": ["combat", 14, COMB+6, 0],
            "/pa/units/orbital/ion_defense/ion_defense.json": ["combat", 17, COMB+7, 1],
            "/pa/units/orbital/basic_ao_defense/basic_ao_defense.json": ["combat", 18, COMB+7, 0],
            "/pa/units/land/nuke_launcher/nuke_launcher.json": ["combat", 19, COMB+8, 1],
            "/pa/units/land/anti_nuke_launcher/anti_nuke_launcher.json": ["combat", 20, COMB+8, 0],

            "/pa/units/land/nuke_launcher/nuke_launcher_ammo.json": ["ammo", 0, AMMO+0, 0],
            "/pa/units/land/anti_nuke_launcher/anti_nuke_launcher_ammo.json": ["ammo", 1, AMMO+0, 0],
            "/pa/units/land/mb4/mb4.json": ["ammo", 5, SUPER+1, 0],
            "/pa/units/air/mb3/mb3.json": ["ammo", 4, SUPER+0, 2],
            "/pa/units/land/mb2/mb2.json": ["ammo", 3, SUPER+0, 1],
            "/pa/units/land/mb1/mb1.json": ["ammo", 2, SUPER+0, 0],

            "/pa/units/land/fabrication_vehicle_adv/fabrication_vehicle_adv.json": ["vehicle", 0, VEH+0, 2],
            "/pa/units/land/fabrication_vehicle/fabrication_vehicle.json": ["vehicle", 12, VEH+0, 0],
            "/pa/units/land/fabrication_vehicle_combat_adv/fabrication_vehicle_combat_adv.json": ["vehicle", 5, VEH+1, 2],
            "/pa/units/land/tank_heavy/tank_heavy.json": ["vehicle", 1, VEH+2, 2],
            "/pa/units/land/tank_heavy_armor/tank_heavy_armor.json": ["vehicle", 2, VEH+3, 2],
            "/pa/units/land/tank_heavy_mortar/tank_heavy_mortar.json": ["vehicle", 3, VEH+4, 2],
            "/pa/units/land/aa_missile_vehicle/aa_missile_vehicle.json": ["vehicle", 4, VEH+5, 2],
            "/pa/units/land/tank_laser_adv/tank_laser_adv.json": ["vehicle", 7, VEH+2, 1],
            "/pa/units/land/tank_armor/tank_armor.json": ["vehicle", 8, VEH+3, 1],
            "/pa/units/land/tank_heavy_artillery/tank_heavy_artillery.json": ["vehicle", 9, VEH+4, 1],
            "/pa/units/land/tank_pd/tank_pd.json": ["vehicle", 11, VEH+6, 1],
            "/pa/units/land/tank_light_laser/tank_light_laser.json": ["vehicle", 13, VEH+2, 0],
            "/pa/units/land/land_scout/land_scout.json": ["vehicle", 14, VEH+3, 0],
            "/pa/units/land/land_aa_1/land_aa_1.json": ["vehicle", 16, VEH+5, 0],
            "/pa/units/land/tank_radar/tank_radar.json": ["vehicle", 17, VEH+6, 0],

            "/pa/units/land/fabrication_bot_adv/fabrication_bot_adv.json": ["bot", 0, BOT+0, 2],
            "/pa/units/land/fabrication_bot/fabrication_bot.json": ["bot", 12, BOT+0, 0],
            "/pa/units/land/fabrication_bot_combat_adv/fabrication_bot_combat_adv.json": ["bot", 11, BOT+1, 2],
            "/pa/units/land/fabrication_bot_combat/fabrication_bot_combat.json": ["bot", 6, BOT+0, 1],
            "/pa/units/land/raptor_bot_1/raptor_bot_1.json": ["bot", 1, BOT+2, 2],
            "/pa/units/land/bot_tactical_missile/bot_tactical_missile.json": ["bot", 2, BOT+3, 2],
            "/pa/units/land/bot_sniper/bot_sniper.json": ["bot", 3, BOT+4, 2],
            "/pa/units/land/bot_grenadier/bot_grenadier.json": ["bot", 4, BOT+5, 2],
            "/pa/units/land/assault_bot_adv/assault_bot_adv.json": ["bot", 7, BOT+2, 1],
            "/pa/units/land/bot_bomb/bot_bomb.json": ["bot", 8, BOT+3, 1],
            "/pa/units/land/bot_artillery_adv/bot_artillery_adv.json": ["bot", 9, BOT+4, 1],
            "/pa/units/land/bot_aa/bot_aa.json": ["bot", 10, BOT+5, 1],
            "/pa/units/land/assault_bot/assault_bot.json": ["bot", 13, BOT+2, 0],
            "/pa/units/land/bot_artillery/bot_artillery.json": ["bot", 14, BOT+3, 0],
            "/pa/units/land/botbase1_art/botbase1_art.json": ["bot", 15, BOT+4, 0],
            "/pa/units/land/botbase1_aa/botbase1_aa.json": ["bot", 16, BOT+5, 0],

            "/pa/units/air/fabrication_aircraft_adv/fabrication_aircraft_adv.json": ["air", 0, AIR+0, 2],
            "/pa/units/air/fabrication_aircraft/fabrication_aircraft.json": ["air", 12, AIR+0, 0],
            "/pa/units/air/fabrication_aircraft_combat/fabrication_aircraft_combat.json": ["air", 6, AIR+0, 1],
            "/pa/units/air/fighter_adv/fighter_adv.json": ["air", 1, AIR+2, 2],
            "/pa/units/air/bomber/bomber.json": ["air", 2, AIR+3, 2],
            "/pa/units/air/bomber_adv/bomber_adv.json": ["air", 3, AIR+4, 2],
            "/pa/units/air/spy_plane/spy_plane.json": ["air", 4, AIR+5, 2],
            "/pa/units/air/interplanetary_fighter/interplanetary_fighter.json": ["air", 5, AIR+6, 2],
            "/pa/units/air/fighter/fighter.json": ["air", 7, AIR+2, 1],
            "/pa/units/air/gunship/gunship.json": ["air", 8, AIR+2, 1],
            "/pa/units/air/transport/transport.json": ["air", 11, AIR+5, 1],
            "/pa/units/air/fighter_basic/fighter_basic.json": ["air", 13, AIR+2, 0],
            "/pa/units/air/bomber_basic/bomber_basic.json": ["air", 14, AIR+3, 0],
            "/pa/units/air/air_scout/air_scout.json": ["air", 16, AIR+5, 0],

            "/pa/units/sea/fabrication_ship_adv/fabrication_ship_adv.json": ["sea", 0, SEA+0, 2],
            "/pa/units/sea/fabrication_sub/fabrication_sub.json": ["sea", 6, SEA+0, 1],
            "/pa/units/sea/fabrication_ship/fabrication_ship.json": ["sea", 12, SEA+0, 0],
            "/pa/units/sea/battleship/battleship.json": ["sea", 1, SEA+1, 2],
            "/pa/units/sea/nuclear_sub/nuclear_sub.json": ["sea", 2, SEA+3, 2],
            "/pa/units/sea/destroyer/destroyer.json": ["sea", 7, SEA+1, 1],
            "/pa/units/sea/attack_sub/attack_sub.json": ["sea", 8, SEA+2, 1],
            "/pa/units/sea/missile_ship/missile_ship.json": ["sea", 9, SEA+3, 1],
            "/pa/units/sea/frigate/frigate.json": ["sea", 10, SEA+4, 1],
            "/pa/units/sea/boat_assault/boat_assault.json": ["sea",13, SEA+1, 0],
            "/pa/units/sea/boat_torpedo/boat_torpedo.json": ["sea",14, SEA+2, 0],
            "/pa/units/sea/boat_aa/boat_aa.json": ["sea", 16, SEA+4, 0],
            "/pa/units/sea/sea_scout/sea_scout.json": ["sea", 17, SEA+5, 0],

            "/pa/units/orbital/orbital_fighter/orbital_fighter.json": ["orbital", 1, ORB+1, 2],
            "/pa/units/orbital/orbital_bombardment/orbital_bombardment.json": ["orbital", 2, ORB+2, 2],
            "/pa/units/orbital/orbital_destroyer/orbital_destroyer.json": ["orbital", 3, ORB+3, 2],
            "/pa/units/orbital/orbital_artillery/orbital_artillery.json": ["orbital", 4, ORB+4, 2],
            "/pa/units/orbital/orbital_factory/orbital_factory.json": ["orbital", 6, ORB+0, 1],
            "/pa/units/orbital/defense_satellite/defense_satellite.json": ["orbital", 7, ORB+1, 1],
            "/pa/units/orbital/orbital_laser/orbital_laser.json": ["orbital", 8, ORB+2, 1],
            "/pa/units/orbital/radar_satellite_adv/radar_satellite_adv.json": ["orbital", 9, ORB+3, 1],
            "/pa/units/orbital/solar_array/solar_array.json": ["orbital", 10, ORB+4, 1],
            "/pa/units/orbital/mining_platform/mining_platform.json": ["orbital", 11, ORB+5, 1],
            "/pa/units/orbital/orbital_fabrication_bot/orbital_fabrication_bot.json": ["orbital", 12, ORB+0, 0],
            "/pa/units/orbital/buzzer/buzzer.json": ["orbital", 13, ORB+1, 0],
            "/pa/units/orbital/orbital_lander/orbital_lander.json": ["orbital", 14, ORB+2, 0],
            "/pa/units/orbital/radar_satellite/radar_satellite.json": ["orbital", 15, ORB+3, 0],
        }
    );
};
