
function BuildHotkeyModel() {
    var self = this;

    var FAC=0;
    var UTIL=FAC+15;
    var COMB=UTIL+6;
    var AMMO=COMB+9;
    var SUPER=AMMO+1;
    var AIR1=SUPER+4;
    var AIR2=AIR1+6;
    var BOT1=AIR2+7;
    var BOT2=BOT1+7;
    var VEH1=BOT2+7;
    var VEH2=VEH1+7;
    var SPEC=VEH2+7;
    var SEA1=SPEC+1;
    var ORB=SEA1+6;
    self.SpecIdToGridMap = ko.observable(
        {
            "/pa/units/air/Afac11/Afac11.json": ["factory", 0, FAC+0, 0],
            "/pa/units/air/Afac12/Afac12.json": ["factory", 1, FAC+0, 1],
            "/pa/units/air/Afac13/Afac13.json": ["factory", 3, FAC+0, 2],
            "/pa/units/air/Afac21/Afac21.json": ["factory", 4, FAC+1, 0],
            "/pa/units/air/Afac22/Afac22.json": ["factory", 5, FAC+1, 1],
            "/pa/units/air/Afac23/Afac23.json": ["factory", 6, FAC+1, 2],
            "/pa/units/land/Bfac11/Bfac11.json": ["factory", 7, FAC+4, 0],
            "/pa/units/land/Bfac12/Bfac12.json": ["factory", 8, FAC+4, 1],
            "/pa/units/land/Bfac13/Bfac13.json": ["factory", 9, FAC+4, 2],
            "/pa/units/land/Bfac21/Bfac21.json": ["factory", 10, FAC+5, 0],
            "/pa/units/land/Bfac22/Bfac22.json": ["factory", 11, FAC+5, 1],
            "/pa/units/land/Bfac23/Bfac23.json": ["factory", 12, FAC+5, 2],
            "/pa/units/land/Vfac11/Vfac11.json": ["factory", 13, FAC+6, 0],
            "/pa/units/land/Vfac12/Vfac12.json": ["factory", 14, FAC+6, 1],
            "/pa/units/land/Vfac13/Vfac13.json": ["factory", 15, FAC+6, 2],
            "/pa/units/land/Vfac21/Vfac21.json": ["factory", 16, FAC+7, 0],
            "/pa/units/land/Vfac22/Vfac22.json": ["factory", 17, FAC+7, 1],
            "/pa/units/land/Vfac23/Vfac23.json": ["factory", 18, FAC+7, 2],
            "/pa/units/sea/Nfac11/Nfac11.json": ["factory", 19, FAC+8, 0],
            "/pa/units/sea/Nfac12/Nfac12.json": ["factory", 20, FAC+8, 1],
            "/pa/units/sea/Nfac13/Nfac13.json": ["factory", 21, FAC+8, 2],
            "/pa/units/orbital/OfaclA0/OfaclA0.json": ["factory", 22, FAC+9, 0],
            "/pa/units/land/Sfcmb11/Sfcmb11.json": ["factory", 23, FAC+10, 0],
            "/pa/units/land/Sfamph11/Sfamph11.json": ["factory", 24, FAC+10, 1],
            "/pa/units/land/Sfnano11/Sfnano11.json": ["factory", 25, FAC+11, 0],
            "/pa/units/land/Sfnano21/Sfnano21.json": ["factory", 36, FAC+11, 1],
            "/pa/units/land/SfucB1/SfucB1.json": ["factory", 27, FAC+12, 0],
            "/pa/units/land/SfucB2/SfucB2.json": ["factory", 28, FAC+12, 1],
            "/pa/units/land/SfucV1/SfucV1.json": ["factory", 29, FAC+13, 0],
            "/pa/units/land/SfucV2/SfucV2.json": ["factory", 30, FAC+13, 1],

            "/pa/units/orbital/SscmA0/SscmA0.json": ["utility", 0, UTIL+0, 2],
            "/pa/units/orbital/SspeA0/SspeA0.json": ["utility", 1, UTIL+0, 1],
            "/pa/units/land/SstpA0/SstpA0.json": ["utility", 2, UTIL+0, 0],
            "/pa/units/land/SradarA3/SradarA3.json": ["utility", 3, UTIL+2, 2],
            "/pa/units/land/SradarA2/SradarA2.json": ["utility", 4, UTIL+2, 1],
            "/pa/units/land/SradarA1/SradarA1.json": ["utility", 5, UTIL+2, 0],
            "/pa/units/orbital/SoradarA3/SoradarA3.json": ["utility", 6, UTIL+3, 2],
            "/pa/units/orbital/SoradarA1/SoradarA1.json": ["utility", 7, UTIL+3, 1],
            "/pa/units/sea/NsonarA1/NsonarA1.json": ["utility", 14, UTIL+3, 0],
            "/pa/units/land/SrepA3/SrepA3.json": ["utility", 8, UTIL+4, 2],
            "/pa/units/land/SrepA1/SrepA1.json": ["utility", 9, UTIL+4, 1],
            "/pa/units/land/SresA1/SresA1.json": ["utility", 10, UTIL+4, 0],
            "/pa/units/land/SrmpA3/SrmpA3.json": ["utility", 11, UTIL+5, 2],
            "/pa/units/land/SrmpA1/SrmpA1.json": ["utility", 12, UTIL+5, 1],
            "/pa/units/land/SrmsA1/SrmsA1.json": ["utility", 13, UTIL+5, 0],

            "/pa/units/land/SdwallA0/SdwallA0.json": ["combat", 0, COMB+0, 0],
            "/pa/units/land/SdmineA0/SdmineA0.json": ["combat", 1, COMB+0, 1],
            "/pa/units/land/Sdal11/Sdal11.json": ["combat", 2, COMB+1, 0],
            "/pa/units/land/Sdal12/Sdal12.json": ["combat", 3, COMB+1, 1],
            "/pa/units/land/Sdal13/Sdal13.json": ["combat", 4, COMB+1, 2],
            "/pa/units/land/Sdal21/Sdal21.json": ["combat", 19, COMB+2, 0],
            "/pa/units/land/Sdal22/Sdal22.json": ["combat", 20, COMB+2, 1],
            "/pa/units/land/Sdal23/Sdal23.json": ["combat", 21, COMB+2, 2],
            "/pa/units/land/Sdart11/Sdart11.json": ["combat", 5, COMB+3, 0],
            "/pa/units/land/Sdart12/Sdart12.json": ["combat", 6, COMB+3, 1],
            "/pa/units/land/Sdart13/Sdart13.json": ["combat", 7, COMB+3, 2],
            "/pa/units/land/Sdart21/Sdart21.json": ["combat", 8, COMB+4, 0],
            "/pa/units/land/Sdtml22/Sdtml22.json": ["combat", 9, COMB+4, 1],
            "/pa/units/land/Sdart23/Sdart23.json": ["combat", 10, COMB+4, 2],
            "/pa/units/land/SdaaA1/SdaaA1.json": ["combat", 11, COMB+5, 0],
            "/pa/units/land/SdaaA2/SdaaA2.json": ["combat", 12, COMB+5, 1],
            "/pa/units/sea/NdanA1/NdanA1.json": ["combat", 13, COMB+6, 0],
            "/pa/units/sea/NdanA2/NdanA2.json": ["combat", 14, COMB+6, 1],
            "/pa/units/orbital/SdaoA1/SdaoA1.json": ["combat", 15, COMB+7, 0],
            "/pa/units/orbital/SdaoA3/SdaoA3.json": ["combat", 16, COMB+7, 2],
            "/pa/units/land/SsndA0/SsndA0.json": ["combat", 17, COMB+8, 0],
            "/pa/units/land/SsnlA0/SsnlA0.json": ["combat", 18, COMB+8, 1],

            "/pa/units/land/nuke_launcher/nuke_launcher_ammo.json": ["ammo", 0, AMMO+0, 1],
            "/pa/units/land/anti_nuke_launcher/anti_nuke_launcher_ammo.json": ["ammo", 1, AMMO+0, 0],

            "/pa/units/land/Xmb1/Xmb1.json": ["ammo", 2, SUPER+0, 0],
            "/pa/units/land/Xmb2/Xmb2.json": ["ammo", 3, SUPER+1, 0],
            "/pa/units/air/Xmb3/Xmb3.json": ["ammo", 4, SUPER+2, 0],
            "/pa/units/land/Xmb4b/Xmb4b.json": ["ammo", 5, SUPER+3, 0],

            "/pa/units/air/Afab11/Afab11.json": ["air", 0, AIR1+0, 0],
            "/pa/units/air/Afab12/Afab12.json": ["air", 1, AIR1+0, 1],
            "/pa/units/air/Afab13/Afab13.json": ["air", 2, AIR1+0, 2],
            "/pa/units/air/Afighter11/Afighter11.json": ["air", 3, AIR1+1, 0],
            "/pa/units/air/Afighter12/Afighter12.json": ["air", 4, AIR1+1, 1],
            "/pa/units/air/Agunship11/Agunship11.json": ["air", 5, AIR1+2, 0],
            "/pa/units/air/Abomber13/Abomber13.json": ["air", 6, AIR1+2, 2],
            "/pa/units/air/Ascout12/Ascout12.json": ["air", 7, AIR1+4, 1],

            "/pa/units/air/Afab21/Afab21.json": ["air", 8, AIR2+0, 0],
            "/pa/units/air/Afab22/Afab22.json": ["air", 9, AIR2+0, 1],
            "/pa/units/air/Afab23/Afab23.json": ["air", 10, AIR2+0, 2],
            "/pa/units/air/Afighter21/Afighter21.json": ["air", 11, AIR2+1, 0],
            "/pa/units/air/Afighter22/Afighter22.json": ["air", 12, AIR2+1, 1],
            "/pa/units/air/Afighter23/Afighter23.json": ["air", 13, AIR2+1, 2],
            "/pa/units/air/Abomber21/Abomber21.json": ["air", 14, AIR2+2, 0],
            "/pa/units/air/Abomber22/Abomber22.json": ["air", 15, AIR2+2, 1],
            "/pa/units/air/Abomber23/Abomber23.json": ["air", 16, AIR2+2, 2],
            "/pa/units/air/Ascout21/Ascout21.json": ["air", 17, AIR2+4, 0],
            "/pa/units/air/AtransportA2/AtransportA2.json": ["air", 18, AIR2+5, 1],

            "/pa/units/land/Bfab1X/Bfab1X.json": ["bot", 26, BOT1-1, 0],
            "/pa/units/land/Bfab11/Bfab11.json": ["bot", 0, BOT1+0, 0],
            "/pa/units/land/Bfab12/Bfab12.json": ["bot", 1, BOT1+0, 1],
            "/pa/units/land/Bfab13/Bfab13.json": ["bot", 2, BOT1+0, 2],
            "/pa/units/land/Bassault21/Bassault21.json": ["bot", 3, BOT1+1, 0],
            "/pa/units/land/Bassault22/Bassault22.json": ["bot", 4, BOT1+1, 1],
            "/pa/units/land/Bassault23/Bassault23.json": ["bot", 5, BOT1+1, 2],
            "/pa/units/land/Bflame21/Bflame21.json": ["bot", 6, BOT1+2, 0],
            "/pa/units/land/Bsupport22/Bsupport22.json": ["bot", 7, BOT1+2, 1],
            "/pa/units/land/Btactical13/Btactical13.json": ["bot", 8, BOT1+2, 2],
            "/pa/units/land/Baa31/Baa31.json": ["bot", 9, BOT1+3, 0],
            "/pa/units/land/Baa23/Baa23.json": ["bot", 10, BOT1+3, 2],
            "/pa/units/land/Bscout33/Bscout33.json": ["bot", 11, BOT1+4, 2],

            "/pa/units/land/Bnano31/Bnano31.json": ["bot", 27, BOT2-1, 0],
            "/pa/units/land/Bfab21/Bfab21.json": ["bot", 12, BOT2+0, 0],
            "/pa/units/land/Bfab22/Bfab22.json": ["bot", 13, BOT2+0, 1],
            "/pa/units/land/Bfab23/Bfab23.json": ["bot", 14, BOT2+0, 2],
            "/pa/units/land/Bassault11/Bassault11.json": ["bot", 16, BOT2+1, 0],
            "/pa/units/land/Bassault12/Bassault12.json": ["bot", 17, BOT2+1, 1],
            "/pa/units/land/Bassault13/Bassault13.json": ["bot", 18, BOT2+1, 2],
            "/pa/units/land/Bmortar21/Bmortar21.json": ["bot", 19, BOT2+2, 0],
            "/pa/units/land/Bbomb31/Bbomb31.json": ["bot", 20, BOT2+2, 1],
            "/pa/units/land/Bsniper23/Bsniper23.json": ["bot", 21, BOT2+2, 2],
            "/pa/units/land/Baa21/Baa21.json": ["bot", 22, BOT2+3, 0],
            "/pa/units/land/Baa32/Baa32.json": ["bot", 23, BOT2+3, 1],
            "/pa/units/land/Bscout31/Bscout31.json": ["bot", 24, BOT2+4, 0],
            "/pa/units/land/Bao32/Bao32.json": ["bot", 25, BOT2+4, 1],

            "/pa/units/land/Vnano11/Vnano11.json": ["vehicle", 27, VEH1-1, 0],
            "/pa/units/land/Vfab11/Vfab11.json": ["vehicle", 0, VEH1+0, 0],
            "/pa/units/land/Vfab12/Vfab12.json": ["vehicle", 1, VEH1+0, 1],
            "/pa/units/land/Vfab13/Vfab13.json": ["vehicle", 2, VEH1+0, 2],
            "/pa/units/land/Vassault11/Vassault11.json": ["vehicle", 3, VEH1+1, 0],
            "/pa/units/land/Vassault12/Vassault12.json": ["vehicle", 4, VEH1+1, 1],
            "/pa/units/land/Vassault13/Vassault13.json": ["vehicle", 5, VEH1+1, 2],
            "/pa/units/land/Vsupport11/Vsupport11.json": ["vehicle", 6, VEH1+2, 0],
            "/pa/units/land/Vmortar12/Vmortar12.json": ["vehicle", 7, VEH1+2, 1],
            "/pa/units/land/Vartillery13/Vartillery13.json": ["vehicle", 8, VEH1+2, 2],
            "/pa/units/land/Vaa11/Vaa11.json": ["vehicle", 9, VEH1+3, 0],
            "/pa/units/land/Vaa13/Vaa13.json": ["vehicle", 10, VEH1+3, 2],
            "/pa/units/land/Vscout11/Vscout11.json": ["vehicle", 11, VEH1+4, 0],
            "/pa/units/land/Vao13/Vao13.json": ["vehicle", 12, VEH1+4, 2],

            "/pa/units/land/Vfab2X/Vfab2X.json": ["vehicle", 26, VEH2-1, 0],
            "/pa/units/land/Vfab21/Vfab21.json": ["vehicle", 13, VEH2+0, 0],
            "/pa/units/land/Vfab22/Vfab22.json": ["vehicle", 14, VEH2+0, 1],
            "/pa/units/land/Vfab23/Vfab23.json": ["vehicle", 15, VEH2+0, 2],
            "/pa/units/land/Vassault21/Vassault21.json": ["vehicle", 16, VEH2+1, 0],
            "/pa/units/land/Vassault22/Vassault22.json": ["vehicle", 17, VEH2+1, 1],
            "/pa/units/land/Vsupport21/Vsupport21.json": ["vehicle", 18, VEH2+2, 0],
            "/pa/units/land/Vsupport22/Vsupport22.json": ["vehicle", 19, VEH2+2, 1],
            "/pa/units/land/Vartillery23/Vartillery23.json": ["vehicle", 20, VEH2+2, 2],
            "/pa/units/land/Vaa21/Vaa21.json": ["vehicle", 21, VEH2+3, 0],
            "/pa/units/land/Vaa22/Vaa22.json": ["vehicle", 22, VEH2+3, 1],
            "/pa/units/land/Vradar21/Vradar21.json": ["vehicle", 23, VEH2+4, 0],
            "/pa/units/land/Vpd22/Vpd22.json": ["vehicle", 24, VEH2+4, 1],
            "/pa/units/land/Vscout23/Vscout23.json": ["vehicle", 25, VEH2+4, 2],

            "/pa/units/sea/Nfab11/Nfab11.json": ["sea", 0, SEA1+0, 0],
            "/pa/units/sea/Nfab12/Nfab12.json": ["sea", 1, SEA1+0, 1],
            "/pa/units/sea/Nfab13/Nfab13.json": ["sea", 2, SEA1+0, 2],
            "/pa/units/sea/Nassault11/Nassault11.json": ["sea", 4, SEA1+1, 0],
            "/pa/units/sea/Nassault12/Nassault12.json": ["sea", 5, SEA1+1, 1],
            "/pa/units/sea/Nassault13/Nassault13.json": ["sea", 6, SEA1+1, 2],
            "/pa/units/sea/Ntorpedo11/Ntorpedo11.json": ["sea", 7, SEA1+2, 0],
            "/pa/units/sea/Ntorpedo12/Ntorpedo12.json": ["sea", 8, SEA1+2, 1],
            "/pa/units/sea/Ntactical13/Ntactical13.json": ["sea", 9, SEA1+2, 2],
            "/pa/units/sea/Naa11/Naa11.json": ["sea", 10, SEA1+3, 0],
            "/pa/units/sea/Naa13/Naa13.json": ["sea", 11, SEA1+3, 2],
            "/pa/units/sea/Nscout11/Nscout11.json": ["sea", 12, SEA1+4, 0],

            "/pa/units/orbital/OfabA0/OfabA0.json": ["orbital", 0, ORB+0, 0],
            "/pa/units/orbital/ObuzzerA0/ObuzzerA0.json": ["orbital", 1, ORB+1, 0],
            "/pa/units/orbital/OradarA1/OradarA1.json": ["orbital", 2, ORB+2, 0],
            "/pa/units/orbital/OtranspA0/OtranspA0.json": ["orbital", 3, ORB+4, 0],
            "/pa/units/orbital/OfacA0/OfacA0.json": ["orbital", 4, ORB+0, 1],
            "/pa/units/orbital/OfighterA0/OfighterA0.json": ["orbital", 5, ORB+1, 1],
            "/pa/units/orbital/OradarA2/OradarA2.json": ["orbital", 6, ORB+2, 1],
            "/pa/units/orbital/OlaserA0/OlaserA0.json": ["orbital", 7, ORB+3, 1],
            "/pa/units/orbital/OrepA0/OrepA0.json": ["orbital", 12, ORB+4, 1],
            "/pa/units/orbital/OdefsatA0/OdefsatA0.json": ["orbital", 8, ORB+0, 2],
            "/pa/units/orbital/OdestrA0/OdestrA0.json": ["orbital", 9, ORB+1, 2],
            "/pa/units/orbital/OartyA0/OartyA0.json": ["orbital", 10, ORB+2, 2],
            "/pa/units/orbital/ObombA0/ObombA0.json": ["orbital", 11, ORB+3, 2],
            "/pa/units/orbital/OrmpA0/OrmpA0.json": ["orbital", 13, ORB+4, 2],

        }
    );
};
